# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGPCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import qdarkstyle

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.top=80 
        self.left=20
        self.width = 1205
        self.height=660
        # MainWindow.resize(1050, 664)
        MainWindow.setGeometry(self.top, self.left, self.width, self.height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 0, 221, 561))
        self.groupBox_2.setObjectName("groupBox_2")

        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 213, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")

        self.gridLayout.addWidget(self.lineEdit_12, 11, 0, 1, 1)
        
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 14, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 12, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 10, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 9, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 7, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 13, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 8, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 15, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 3, 1, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 4, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 5, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 6, 1, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout.addWidget(self.spinBox_8, 7, 1, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout.addWidget(self.spinBox_9, 8, 1, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout.addWidget(self.spinBox_10, 9, 1, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout.addWidget(self.spinBox_11, 10, 1, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout.addWidget(self.spinBox_12, 11, 1, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout.addWidget(self.spinBox_13, 12, 1, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout.addWidget(self.spinBox_14, 13, 1, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout.addWidget(self.spinBox_15, 14, 1, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout.addWidget(self.spinBox_16, 15, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(560, 0, 221, 561))
        self.groupBox_3.setObjectName("groupBox_3")

        self.plainTextEdit = QtWidgets.QListWidget(self.groupBox_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 20, 221, 541))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 588, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.submitdata)
        self.pushButton.setText("Send")
        self.pushButton.setStyleSheet('background: green; color: #fff;')
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 0, 321, 561))
        self.groupBox_4.setObjectName("groupBox_4")
        
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 321, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_2.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_2)

        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox)

        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_3.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_3)

        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_4.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_4)

        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_5.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_5)

        self.comboBox_6 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_6.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_6)

        self.comboBox_7 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_7.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_7)

        self.comboBox_8 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_8.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_8)

        self.comboBox_9 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_9.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_9)

        self.comboBox_10 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_10.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_10)

        self.comboBox_11 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_11.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_11)

        self.comboBox_12 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_12.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_12)

        self.comboBox_13 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_13.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_13)

        self.comboBox_14 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_14.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_14)

        self.comboBox_15 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_15.setObjectName("comboBox_15")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_15.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_15)

        self.comboBox_16 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_16.setObjectName("comboBox_16")
        self.courselist = ["Choose Your course", "DATABASE SYSTEM", "OPERATING SYSTEM", "DATA STRUCTURE", "BOOLIAN ALGEBRA"]
        self.comboBox_16.addItems(self.courselist)
        self.verticalLayout.addWidget(self.comboBox_16)

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(790, 0, 91, 561))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 91, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_2.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_2.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_2.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_2.addWidget(self.lineEdit_21)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_2.addWidget(self.lineEdit_17)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_2.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_2.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_2.addWidget(self.lineEdit_24)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.verticalLayout_2.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.verticalLayout_2.addWidget(self.lineEdit_26)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.verticalLayout_2.addWidget(self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.verticalLayout_2.addWidget(self.lineEdit_28)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.verticalLayout_2.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.verticalLayout_2.addWidget(self.lineEdit_30)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.verticalLayout_2.addWidget(self.lineEdit_32)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.verticalLayout_2.addWidget(self.lineEdit_31)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(900, 0, 291, 340))
        self.groupBox_5.setObjectName("groupBox_5")

        self.plainTextEdit_2 = QtWidgets.QListWidget(self.groupBox_5)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 20, 291, 151))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")

        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(10, 190, 101, 17))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 78, 17))
        self.label_2.setObjectName("label_2")

        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_33.setGeometry(QtCore.QRect(120, 180, 113, 36))
        self.lineEdit_33.setObjectName("lineEdit_33")

        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_34.setGeometry(QtCore.QRect(120, 220, 113, 36))
        self.lineEdit_34.setObjectName("lineEdit_34")

        self.label_333 = QtWidgets.QLabel(self.groupBox_5)
        self.label_333.setGeometry(QtCore.QRect(10, 270, 130, 17))
        self.label_333.setObjectName("label_333")
        self.label_333.setText("Semester-Count")

        self.lineEdit_355 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_355.setGeometry(QtCore.QRect(120, 260, 113, 36))
        self.lineEdit_355.setObjectName("lineEdit_355")

        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(900, 350, 291, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(0, 20, 291, 151))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")

        # self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_2.setGeometry(QtCore.QRect(590, 590, 131, 31))
        # self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_2.clicked.connect(self.reg)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(980, 530, 131, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.finalCGP)
        self.pushButton_3.setText("Cummulative")
        self.pushButton_3.setStyleSheet('background: green; color: #fff;')

        # self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_4.setGeometry(QtCore.QRect(920, 480, 131, 31))
        # self.pushButton_4.setObjectName("pushButton_4")
        # self.pushButton_4.clicked.connect(self.getTotalscore)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1210, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        # self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "Total Cal"))
        self.label_2.setText(_translate("MainWindow", "credit Load"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Result Comment"))
        # self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        # self.pushButton_3.setText(_translate("MainWindow", "Submit"))
        # self.pushButton_4.setText(_translate("MainWindow", "Submit"))

    def submitdata(self):
        self.plainTextEdit.clear()
        self.combo_item1 = self.comboBox_2.currentText()
        self.combo_item2 = self.comboBox.currentText()
        self.combo_item3 = self.comboBox_3.currentText()
        self.combo_item4 = self.comboBox_4.currentText()
        self.combo_item5 = self.comboBox_5.currentText()
        self.combo_item6 = self.comboBox_6.currentText()
        self.combo_item7 = self.comboBox_7.currentText()
        self.combo_item8 = self.comboBox_8.currentText()
        self.combo_item9 = self.comboBox_9.currentText()
        self.combo_item10 = self.comboBox_10.currentText()
        self.combo_item11 = self.comboBox_11.currentText()
        self.combo_item12 = self.comboBox_12.currentText()
        self.combo_item13 = self.comboBox_13.currentText()
        self.combo_item14 = self.comboBox_14.currentText()
        self.combo_item15 = self.comboBox_15.currentText()
        self.combo_item16 = self.comboBox_16.currentText()

        #LineEdit Section 
        # self.lineEdit.setText()

        self.listme = [f'{self.combo_item1} = {self.lineEdit.text()}',
                    f'{self.combo_item2} = {self.lineEdit_2.text()}',
                    f'{self.combo_item3} = {self.lineEdit_3.text()}',
                    f'{self.combo_item4} = {self.lineEdit_4.text()}',
                    f'{self.combo_item5} = {self.lineEdit_5.text()}',
                    f'{self.combo_item6} = {self.lineEdit_6.text()}',
                    f'{self.combo_item7} = {self.lineEdit_7.text()}',
                    f'{self.combo_item8} = {self.lineEdit_8.text()}',
                    f'{self.combo_item9} = {self.lineEdit_9.text()}',
                    f'{self.combo_item10} = {self.lineEdit_10.text()}',
                    f'{self.combo_item11} = {self.lineEdit_11.text()}',
                    f'{self.combo_item12} = {self.lineEdit_12.text()}',
                    f'{self.combo_item13} = {self.lineEdit_13.text()}',
                    f'{self.combo_item14} = {self.lineEdit_14.text()}',
                    f'{self.combo_item15} = {self.lineEdit_15.text()}',
                    f'{self.combo_item16} = {self.lineEdit_16.text()}',]
        self.plainTextEdit.addItems(self.listme)


        # global Excellent, Vgood, Good, Pass,Fail

        Excellent='A'
        Vgood='B'
        Good='C'
        Pass='D'
        Fail='E'


            #Logic of E1 Display
        try:


            if int(self.lineEdit.text()) >= 70:
                self.lineEdit_18.setText(Excellent)
            elif int(self.lineEdit.text()) >= 60:
                self.lineEdit_18.setText(Vgood)
            elif int(self.lineEdit.text()) >= 50:
                self.lineEdit_18.setText(Good)
            elif int(self.lineEdit.text()) >= 40:
                self.lineEdit_18.setText(Pass)
            elif int(self.lineEdit.text()) >= 30:
                self.lineEdit_18.setText(Fail)
            elif int(self.lineEdit.text()) <= 29:
                self.lineEdit_18.setText(Fail)
            

            # Logic of E3 Display

            if int(self.lineEdit_2.text()) >=70:
                self.lineEdit_19.setText(Excellent)
            elif int(self.lineEdit_2.text()) >=60:
                self.lineEdit_19.setText(Vgood)
            elif int(self.lineEdit_2.text()) >=50:
                self.lineEdit_19.setText(Good)
            elif int(self.lineEdit_2.text()) >=40:
                self.lineEdit_19.setText(Pass)
            elif int(self.lineEdit_2.text()) >=30:
                self.lineEdit_19.setText(Fail)
            elif int(self.lineEdit_2.text()) <=29:
                self.lineEdit_19.setText(Fail)

            # Logic of E5 Display

            if int(self.lineEdit_3.text()) >= 70:
                self.lineEdit_20.setText(Excellent)
            elif int(self.lineEdit_3.text()) >= 60:
                self.lineEdit_20.setText(Vgood)
            elif int(self.lineEdit_3.text()) >= 50:
                self.lineEdit_20.setText(Good)
            elif int(self.lineEdit_3.text()) >= 40:
                self.lineEdit_20.setText(Pass)
            elif int(self.lineEdit_3.text()) >= 30:
                self.lineEdit_20.setText(Fail)
            elif int(self.lineEdit_3.text()) <= 29:
                self.lineEdit_20.setText(Fail)

            # Logic of E7 Display

            if int(self.lineEdit_4.text()) >= 70:
                self.lineEdit_21.setText(Excellent)
            elif int(self.lineEdit_4.text()) >= 60:
                self.lineEdit_21.setText(Vgood)
            elif int(self.lineEdit_4.text()) >= 50:
                self.lineEdit_21.setText(Good)
            elif int(self.lineEdit_4.text()) >= 40:
                self.lineEdit_21.setText(Pass)
            elif int(self.lineEdit_4.text()) >= 30:
                self.lineEdit_21.setText(Fail)
            elif int(self.lineEdit_4.text()) <= 29:
                self.lineEdit_21.setText(Fail)

            # Logic of E9 Display

            if int(self.lineEdit_5.text()) >= 70:
                self.lineEdit_17.setText(Excellent)
            elif int(self.lineEdit_5.text()) >= 60:
                self.lineEdit_17.setText(Vgood)
            elif int(self.lineEdit_5.text()) >= 50:
                self.lineEdit_17.setText(Good)
            elif int(self.lineEdit_5.text()) >= 40:
                self.lineEdit_17.setText(Pass)
            elif int(self.lineEdit_5.text()) >= 30:
                self.lineEdit_17.setText(Fail)
            elif int(self.lineEdit_5.text()) <= 29:
                self.lineEdit_17.setText(Fail)
            # Logic of E11 Display

            if int(self.lineEdit_6.text()) >= 70:
                self.lineEdit_22.setText(Excellent)
            elif int(self.lineEdit_6.text()) >= 60:
                self.lineEdit_22.setText(Vgood)
            elif int(self.lineEdit_6.text()) >= 50:
                self.lineEdit_22.setText(Good)
            elif int(self.lineEdit_6.text()) >= 40:
                self.lineEdit_22.setText(Pass)
            elif int(self.lineEdit_6.text()) >= 30:
                self.lineEdit_22.setText(Fail)
            elif int(self.lineEdit_6.text()) <= 29:
                self.lineEdit_22.setText(Fail)

            # Logic of E13 Display

            if int(self.lineEdit_7.text()) >= 70:
                self.lineEdit_23.setText(Excellent)
            elif int(self.lineEdit_7.text()) >= 60:
                self.lineEdit_23.setText(Vgood)
            elif int(self.lineEdit_7.text()) >= 50:
                self.lineEdit_23.setText(Good)
            elif int(self.lineEdit_7.text()) >= 40:
                self.lineEdit_23.setText(Pass)
            elif int(self.lineEdit_7.text()) >= 30:
                self.lineEdit_23.setText(Fail)
            elif int(self.lineEdit_7.text()) <= 29:
                self.lineEdit_23.setText(Fail)


            # Logic of E15 Display

            if int(self.lineEdit_8.text()) >= 70:
                self.lineEdit_24.setText(Excellent)
            elif int(self.lineEdit_8.text()) >= 60:
                self.lineEdit_24.setText(Vgood)
            elif int(self.lineEdit_8.text()) >= 50:
                self.lineEdit_24.setText(Good)
            elif int(self.lineEdit_8.text()) >= 40:
                self.lineEdit_24.setText(Pass)
            elif int(self.lineEdit_8.text()) >= 30:
                self.lineEdit_24.setText(Fail)
            elif int(self.lineEdit_8.text()) <= 29:
                self.lineEdit_24.setText(Fail)


            # Logic of E17 Display

            if int(self.lineEdit_9.text()) >= 70:
                self.lineEdit_25.setText(Excellent)
            elif int(self.lineEdit_9.text()) >= 60:
                self.lineEdit_25.setText(Vgood)
            elif int(self.lineEdit_9.text()) >= 50:
                self.lineEdit_25.setText(Good)
            elif int(self.lineEdit_9.text()) >= 40:
                self.lineEdit_25.setText(Pass)
            elif int(self.lineEdit_9.text()) >= 30:
                self.lineEdit_25.setText(Fail)
            elif int(self.lineEdit_9.text()) <= 29:
                self.lineEdit_25.setText(Fail)

                # Logic of E19 Display

            if int(self.lineEdit_10.text()) >= 70:
                self.lineEdit_26.setText(Excellent)
            elif int(self.lineEdit_10.text()) >= 60:
                self.lineEdit_26.setText(Vgood)
            elif int(self.lineEdit_10.text()) >= 50:
                self.lineEdit_26.setText(Good)
            elif int(self.lineEdit_10.text()) >= 40:
                self.lineEdit_26.setText(Pass)
            elif int(self.lineEdit_10.text()) >= 30:
                self.lineEdit_26.setText(Fail)
            elif int(self.lineEdit_10.text()) <= 29:
                self.lineEdit_26.setText(Fail)


                # Logic of E21 Display

            if int(self.lineEdit_11.text()) >= 70:
                self.lineEdit_27.setText(Excellent)
            elif int(self.lineEdit_11.text()) >= 60:
                self.lineEdit_27.setText(Vgood)
            elif int(self.lineEdit_11.text()) >= 50:
                self.lineEdit_27.setText(Good)
            elif int(self.lineEdit_11.text()) >= 40:
                self.lineEdit_27.setText(Pass)
            elif int(self.lineEdit_11.text()) >= 30:
                self.lineEdit_27.setText(Fail)
            elif int(self.lineEdit_11.text()) <= 29:
                self.lineEdit_27.setText(Fail)

                # Logic of E23 Display

            if int(self.lineEdit_12.text()) >= 70:
                self.lineEdit_28.setText(Excellent)
            elif int(self.lineEdit_12.text()) >= 60:
                self.lineEdit_28.setText(Vgood)
            elif int(self.lineEdit_12.text()) >= 50:
                self.lineEdit_28.setText(Good)
            elif int(self.lineEdit_12.text()) >= 40:
                self.lineEdit_28.setText(Pass)
            elif int(self.lineEdit_12.text()) >= 30:
                self.lineEdit_28.setText(Fail)
            elif int(self.lineEdit_12.text()) <= 29:
                self.lineEdit_28.setText(Fail)

                # Logic of E25 Display

            if int(self.lineEdit_13.text()) >= 70:
                self.lineEdit_29.setText(Excellent)
            elif int(self.lineEdit_13.text()) >= 60:
                self.lineEdit_29.setText(Vgood)
            elif int(self.lineEdit_13.text()) >= 50:
                self.lineEdit_29.setText(Good)
            elif int(self.lineEdit_13.text()) >= 40:
                self.lineEdit_29.setText(Pass)
            elif int(self.lineEdit_13.text()) >= 30:
                self.lineEdit_29.setText(Fail)
            elif int(self.lineEdit_13.text()) <= 29:
                self.lineEdit_29.setText(Fail)

                # Logic of E27 Display

            if int(self.lineEdit_14.text()) >= 70:
                self.lineEdit_30.setText(Excellent)
            elif int(self.lineEdit_14.text()) >= 60:
                self.lineEdit_30.setText(Vgood)
            elif int(self.lineEdit_14.text()) >= 50:
                self.lineEdit_30.setText(Good)
            elif int(self.lineEdit_14.text()) >= 40:
                self.lineEdit_30.setText(Pass)
            elif int(self.lineEdit_14.text()) >= 30:
                self.lineEdit_30.setText(Fail)
            elif int(self.lineEdit_14.text()) <= 29:
                self.lineEdit_30.setText(Fail)

                # Logic of E29 Display

            if int(self.lineEdit_15.text()) >= 70:
                self.lineEdit_32.setText(Excellent)
            elif int(self.lineEdit_15.text()) >= 60:
                self.lineEdit_32.setText(Vgood)
            elif int(self.lineEdit_15.text()) >= 50:
                self.lineEdit_32.setText(Good)
            elif int(self.lineEdit_15.text()) >= 40:
                self.lineEdit_32.setText(Pass)
            elif int(self.lineEdit_15.text()) >= 30:
                self.lineEdit_32.setText(Fail)
            elif int(self.lineEdit_15.text()) <= 29:
                self.lineEdit_32.setText(Fail)

                # Logic of E31 Display

            if int(self.lineEdit_16.text()) >= 70:
                self.lineEdit_31.setText(Excellent)
            elif int(self.lineEdit_16.text()) >= 60:
                self.lineEdit_31.setText(Vgood)
            elif int(self.lineEdit_16.text()) >= 50:
                self.lineEdit_31.setText(Good)
            elif int(self.lineEdit_16.text()) >= 40:
                self.lineEdit_31.setText(Pass)
            elif int(self.lineEdit_16.text()) >= 30:
                self.lineEdit_31.setText(Fail)
            elif int(self.lineEdit_16.text()) <= 29:
                self.lineEdit_31.setText(Fail)

            else:
                print("error")
        except ValueError:
            pass
        self.getTotalscore()

        
    def getTotalscore(self):

        score1=0
        score2=0
        score3=0
        score4=0
        score5=0
        score6=0
        score7=0
        score8=0
        score9=0
        score10=0
        score11=0
        score12=0
        score13=0
        score14=0
        score15=0
        score16=0
            # score1
        if self.lineEdit_18.text() =='A':
            score1= int(self.spinBox.text()) * 5
        elif self.lineEdit_18.text() =='B':
            score1= int(self.spinBox.text()) * 4
        if self.lineEdit_18.text() =='C':
            score1= int(self.spinBox.text()) * 3
        if self.lineEdit_18.text() =='D':
            score1= int(self.spinBox.text()) * 2
        if self.lineEdit_18.text() =='E':
            score1= int(self.spinBox.text()) * 1

        #     # score 2
        if self.lineEdit_19.text() == 'A':
            score2 = int(self.spinBox_2.text()) * 5
        elif self.lineEdit_19.text() == 'B':
            score2 = int(self.spinBox_2.text()) * 4
        if self.lineEdit_19.text() == 'C':
            score2 = int(self.spinBox_2.text()) * 3
        if self.lineEdit_19.text() == 'D':
            score2 = int(self.spinBox_2.text()) * 2
        if self.lineEdit_19.text() == 'E':
            score2 = int(self.spinBox_2.text()) * 1

        # # score3

        if self.lineEdit_20.text() == 'A':
            score3 = int(self.spinBox_3.text()) * 5
        elif self.lineEdit_20.text() == 'B':
            score3 = int(self.spinBox_3.text()) * 4
        if self.lineEdit_20.text() == 'C':
            score3 = int(self.spinBox_3.text()) * 3
        if self.lineEdit_20.text() == 'D':
            score3 = int(self.spinBox_3.text()) * 2
        if self.lineEdit_20.text() == 'E':
            score3 = int(self.spinBox_3.text()) * 1

        #score4
        if self.lineEdit_21.text() == 'A':
            score4 = int(self.spinBox_4.text()) * 5
        elif self.lineEdit_21.text() == 'B':
            score4 = int(self.spinBox_4.text()) * 4
        if self.lineEdit_21.text() == 'C':
            score4 = int(self.spinBox_4.text()) * 3
        if self.lineEdit_21.text() == 'D':
            score4 = int(self.spinBox_4.text()) * 2
        if self.lineEdit_21.text() == 'E':
            score4 = int(self.spinBox_4.text()) * 1

        # # score5

        if self.lineEdit_17.text() == 'A':
            score5 = int(self.spinBox_5.text()) * 5
        elif self.lineEdit_17.text() == 'B':
            score5 = int(self.spinBox_5.text()) * 4
        if self.lineEdit_17.text() == 'C':
            score5 = int(self.spinBox_5.text()) * 3
        if self.lineEdit_17.text() == 'D':
            score5 = int(self.spinBox_5.text()) * 2
        if self.lineEdit_17.text() == 'E':
            score5 = int(self.spinBox_5.text()) * 1

        # score6

        if self.lineEdit_22.text() == 'A':
            score6 = int(self.spinBox_6.text()) * 5
        elif self.lineEdit_22.text() == 'B':
            score6 = int(self.spinBox_6.text()) * 4
        if self.lineEdit_22.text() == 'C':
            score6 = int(self.spinBox_6.text()) * 3
        if self.lineEdit_22.text() == 'D':
            score6 = int(self.spinBox_6.text()) * 2
        if self.lineEdit_22.text() == 'E':
            score6 = int(self.spinBox_6.text()) * 1


        # score7

        if self.lineEdit_23.text() == 'A':
            score7 = int(self.spinBox_7.text()) * 5
        elif self.lineEdit_23.text() == 'B':
            score7 = int(self.spinBox_7.text()) * 4
        if self.lineEdit_23.text() == 'C':
            score7 = int(self.spinBox_7.text()) * 3
        if self.lineEdit_23.text() == 'D':
            score7 = int(self.spinBox_7.text()) * 2
        if self.lineEdit_23.text() == 'E':
            score7 = int(self.spinBox_7.text()) * 1

        # # score8

        if self.lineEdit_24.text() == 'A':
            score8 = int(self.spinBox_9.text()) * 5
        elif self.lineEdit_24.text() == 'B':
            score8 = int(self.spinBox_9.text()) * 4
        if self.lineEdit_24.text() == 'C':
            score8 = int(self.spinBox_9.text()) * 3
        if self.lineEdit_24.text() == 'D':
            score8 = int(self.spinBox_9.text()) * 2
        if self.lineEdit_24.text() == 'E':
            score8 = int(self.spinBox_9.text()) * 1

        # score9

        if self.lineEdit_25.text() == 'A':
            score9 = int(self.spinBox_8.text()) * 5
        elif self.lineEdit_25.text() == 'B':
            score9 = int(self.spinBox_8.text()) * 4
        if self.lineEdit_25.text() == 'C':
            score9 = int(self.spinBox_8.text()) * 3
        if self.lineEdit_25.text() == 'D':
            score9 = int(self.spinBox_8.text()) * 2
        if self.lineEdit_25.text() == 'E':
            score9 = int(self.spinBox_8.text()) * 1

        # score10

        if self.lineEdit_26.text() == 'A':
            score10 = int(self.spinBox_10.text()) * 5
        elif self.lineEdit_26.text() == 'B':
            score10 = int(self.spinBox_10.text()) * 4
        if self.lineEdit_26.text() == 'C':
            score10 = int(self.spinBox_10.text()) * 3
        if self.lineEdit_26.text() == 'D':
            score10 = int(self.spinBox_10.text()) * 2
        if self.lineEdit_26.text() == 'E':
            score10 = int(self.spinBox_10.text()) * 1

        # score11

        if self.lineEdit_27.text() == 'A':
            score11 = int(self.spinBox_11.text()) * 5
        elif self.lineEdit_27.text() == 'B':
            score11 = int(self.spinBox_11.text()) * 4
        if self.lineEdit_27.text() == 'C':
            score11 = int(self.spinBox_11.text()) * 3
        if self.lineEdit_27.text() == 'D':
            score11 = int(self.spinBox_11.text()) * 2
        if self.lineEdit_27.text() == 'E':
            score11 = int(self.spinBox_11.text()) * 1

        # score12

        if self.lineEdit_28.text() == 'A':
            score12 = int(self.spinBox_12.text()) * 5
        elif self.lineEdit_28.text() == 'B':
            score12 = int(self.spinBox_12.text()) * 4
        if self.lineEdit_28.text() == 'C':
            score12 = int(self.spinBox_12.text()) * 3
        if self.lineEdit_28.text() == 'D':
            score12 = int(self.spinBox_12.text()) * 2
        if self.lineEdit_28.text() == 'E':
            score12 = int(self.spinBox_12.text()) * 1

        # score13

        if self.lineEdit_29.text() == 'A':
            score13 = int(self.spinBox_13.text()) * 5
        elif self.lineEdit_29.text() == 'B':
            score13 = int(self.spinBox_13.text()) * 4
        if self.lineEdit_29.text() == 'C':
            score13 = int(self.spinBox_13.text()) * 3
        if self.lineEdit_29.text() == 'D':
            score13 = int(self.spinBox_13.text()) * 2
        if self.lineEdit_29.text() == 'E':
            score13 = int(self.spinBox_13.text()) * 1

        # score14

        if self.lineEdit_30.text() == 'A':
            score14 = int(self.spinBox_14.text()) * 5
        elif self.lineEdit_30.text() == 'B':
            score14 = int(self.spinBox_14.text()) * 4
        if self.lineEdit_30.text() == 'C':
            score14 = int(self.spinBox_14.text()) * 3
        if self.lineEdit_30.text() == 'D':
            score14 = int(self.spinBox_14.text()) * 2
        if self.lineEdit_30.text() == 'E':
            score14 = int(self.spinBox_14.text()) * 1

        # score15

        if self.lineEdit_31.text() == 'A':
            score15 = int(self.spinBox_15.text()) * 5
        elif self.lineEdit_31.text() == 'B':
            score15 = int(self.spinBox_15.text()) * 4
        if self.lineEdit_31.text() == 'C':
            score15 = int(self.spinBox_15.text()) * 3
        if self.lineEdit_31.text() == 'D':
            score15 = int(self.spinBox_15.text()) * 2
        if self.lineEdit_31.text() == 'E':
            score15 = int(self.spinBox_15.text()) * 1

        # score16

        if self.lineEdit_31.text() == 'A':
            score16 = int(self.spinBox_16.text()) * 5
        elif self.lineEdit_31.text() == 'B':
            score16 = int(self.spinBox_16.text()) * 4
        if self.lineEdit_31.text() == 'C':
            score16 = int(self.spinBox_16.text()) * 3
        if self.lineEdit_31.text() == 'D':
            score16 = int(self.spinBox_16.text()) * 2
        if self.lineEdit_31.text() == 'E':
            score16 = int(self.spinBox_16.text()) * 1

        # self.lineEdit_33.setText(score1)
        self.plainTextEdit_2.clear()
        self.listme2 = [f'{score1}',
                        f'{score2}',
                        f'{score3}',
                        f'{score4}',
                        f'{score5}',
                        f'{score6}',
                        f'{score7}',
                        f'{score8}',
                        f'{score9}',
                        f'{score10}',
                        f'{score11}',
                        f'{score12}',
                        f'{score13}',
                        f'{score14}',
                        f'{score15}',
                        f'{score16}',]
        self.plainTextEdit_2.addItems(self.listme2)
        self.result = (score1 + score2) +(score3 + score4) + (score5 + score6) +(score7 + score8) + (score9 + score10) +(score11 + score12) + (score13 + score14) +(score15 + score16)
        self.lineEdit_33.setText(str(self.result))
        self.spinbox_result = int(self.spinBox.text()) + int(self.spinBox_2.text())
        self.spinbox_result_text = str(self.spinbox_result)
        self.integer = str(self.lineEdit_34.setText(self.spinbox_result_text))
        self.lineEdit_355.setText("1")

        # self.spinbox_result = (self.spinBox.text() + self.spinBox_2.text()) +(self.spinBox_3.text() +self.spinBox_4.text()) + (self.spinBox_5.text() +self.spinBox_6.text()) + (self.spinBox_7.text() + (self.spinBox_8.text()) + (self.spinBox_9.text()) + self.spinBox_10.text()) +(self.spinBox_11 + self.spinBox_12.text()) + (self.spinBox_13.text() + self.spinBox_14.text()) +(self.spinBox_15.text() + self.spinBox_16.text())
        # self.plainTextEdit_3.setPlainText()

    def finalCGP(self):

        self.integer = int(self.lineEdit_34.text())
        self.cgp = (int(self.lineEdit_33.text()) / self.integer)
        self.bb = (float(self.cgp) / int(self.lineEdit_355.text()))
        self.plainTextEdit_3.setPlainText(str(self.bb))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # app.setStyleSheet(qdarkstyle.load_stylesheet())
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
